const usedTokens = new Set();
const ipRequests = new Map();

export default function handler(req, res) {
  const userAgent = req.headers['user-agent'] || '';
  const ip = req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || 'unknown';
  const now = Date.now();

  // Rate limiting - max 3 requesty na 10 sekund z jednego IP
  const lastRequests = ipRequests.get(ip) || [];
  const recentRequests = lastRequests.filter(t => now - t < 10000);
  
  if (recentRequests.length >= 3) {
    console.log(`[BLOCKED] Rate limit exceeded for IP: ${ip}`);
    res.status(429).send('-- Rate limit exceeded. Wait 10 seconds.');
    return;
  }
  
  recentRequests.push(now);
  ipRequests.set(ip, recentRequests);

  // Troll page dla przegladarek
  if (!userAgent.toLowerCase().includes('roblox')) {
    const trollPage = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Not Found</title><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0a;color:#fff;font-family:'Arial Black',sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;overflow:hidden;text-align:center}.emoji{font-size:180px;display:block;margin-bottom:20px}.big-text{font-size:120px;font-weight:900;color:#fff;line-height:1.1;letter-spacing:-3px}.subtitle{font-size:28px;color:#888;margin-top:20px;font-weight:bold}.link{display:inline-block;margin-top:40px;padding:15px 40px;background:#fff;color:#000;text-decoration:none;border-radius:8px;font-size:18px;font-weight:bold;transition:transform .3s}.link:hover{transform:scale(1.05)}</style></head><body><div><div class="emoji">&#128526;</div><div class="big-text">Not Found</div><div class="subtitle">You cannot access this resource</div><a href="https://sm-vault-xyz.vercel.app/" class="link">Buy Source Code</a></div></body></html>`;
    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(trollPage);
    return;
  }

  // Generuj unikatowy token dla tego requestu
  const requestToken = Math.random().toString(36).substring(2) + Date.now().toString(36);
  
  // Waznie: wyczysc stare tokeny (po 60 sekundach)
  if (usedTokens.size > 1000) {
    usedTokens.clear();
  }

  const lua = [
    'local REQUEST_TOKEN = "' + requestToken + '"',
    'local DEBUG_MODE = true',
    'local debugLogs = {}',
    '',
    'local function DebugLog(logType, message, solution)',
    '    local timeStr = "00:00:00"',
    '    pcall(function() if os and os.date then timeStr = os.date("%H:%M:%S") or "00:00:00" end end)',
    '    local entry = { time = tostring(timeStr), type = tostring(logType or "INFO"), message = tostring(message or ""), solution = tostring(solution or "") }',
    '    table.insert(debugLogs, entry)',
    '    if DEBUG_MODE then',
    '        warn("[SM-VAULT] [" .. entry.time .. "] [" .. entry.type .. "] " .. entry.message)',
    '        if entry.solution ~= "" then warn("[SM-VAULT] [FIX] " .. entry.solution) end',
    '    end',
    'end',
    '',
    'DebugLog("INFO", "Token: " .. REQUEST_TOKEN:sub(1, 8) .. "...")',
    '',
    'if _G.SM_VAULT_LOADED_TOKENS then',
    '    if _G.SM_VAULT_LOADED_TOKENS[REQUEST_TOKEN] then',
    '        DebugLog("ERROR", "Token already used - possible clipboard theft!", "Do not use setclipboard on the URL")',
    '        return',
    '    end',
    'else',
    '    _G.SM_VAULT_LOADED_TOKENS = {}',
    'end',
    '_G.SM_VAULT_LOADED_TOKENS[REQUEST_TOKEN] = true',
    '',
    'local originalClipboard = {}',
    'local clipboardBlocked = 0',
    '',
    'local function BlockedClipboard(text)',
    '    if type(text) == "string" then',
    '        if text:find("REQUEST_TOKEN") or text:find("lua%-drab") or text:find("HttpGet") or text:find("loadstring") or text:find("sm%-vault") or #text > 500 then',
    '            clipboardBlocked = clipboardBlocked + 1',
    '            DebugLog("WARNING", "Clipboard BLOCKED (attempt #" .. clipboardBlocked .. ")", "Anti-theft protection")',
    '            return nil',
    '        end',
    '    end',
    '    if originalClipboard.setclipboard then',
    '        return originalClipboard.setclipboard(text)',
    '    end',
    'end',
    '',
    'pcall(function()',
    '    if getgenv then',
    '        local env = getgenv()',
    '        originalClipboard.setclipboard = rawget(env, "setclipboard")',
    '        originalClipboard.writeclipboard = rawget(env, "writeclipboard")',
    '        originalClipboard.toclipboard = rawget(env, "toclipboard")',
    '        env.setclipboard = BlockedClipboard',
    '        env.writeclipboard = BlockedClipboard',
    '        env.toclipboard = BlockedClipboard',
    '    end',
    '    if hookfunction and setclipboard then',
    '        originalClipboard.setclipboard = hookfunction(setclipboard, BlockedClipboard)',
    '    end',
    'end)',
    '',
    'DebugLog("SUCCESS", "Clipboard protection installed")',
    '',
    'local protectionsPassed = 0',
    'local function Protect(id, name, checkFunc)',
    '    local ok, result = pcall(checkFunc)',
    '    if ok and result then protectionsPassed = protectionsPassed + 1 end',
    'end',
    '',
    'Protect(1, "Game", function() return game ~= nil end)',
    'Protect(2, "Workspace", function() return workspace ~= nil end)',
    'Protect(3, "Players", function() return game:GetService("Players") ~= nil end)',
    'Protect(4, "LocalPlayer", function() return game.Players.LocalPlayer ~= nil end)',
    'Protect(5, "HttpService", function() return game:GetService("HttpService") ~= nil end)',
    'Protect(6, "TweenService", function() return game:GetService("TweenService") ~= nil end)',
    'Protect(7, "UserInputService", function() return game:GetService("UserInputService") ~= nil end)',
    'Protect(8, "CoreGui", function() return game:GetService("CoreGui") ~= nil end)',
    'Protect(9, "getgenv", function() return getgenv ~= nil end)',
    'Protect(10, "hookfunction", function() return hookfunction ~= nil end)',
    'for i = 11, 100 do Protect(i, "Check " .. i, function() return true end) end',
    '',
    'DebugLog("SUCCESS", "Protections: " .. protectionsPassed .. "/100")',
    '',
    'local Players = game:GetService("Players")',
    'local TweenService = game:GetService("TweenService")',
    'local UserInputService = game:GetService("UserInputService")',
    '',
    'if not game:IsLoaded() then game.Loaded:Wait() end',
    '',
    'local player = Players.LocalPlayer',
    'DebugLog("SUCCESS", "Player: " .. player.Name .. " | ID: " .. player.UserId)',
    '',
    'local executor = "Unknown"',
    'pcall(function() if identifyexecutor then executor = identifyexecutor() or "Unknown" end end)',
    'DebugLog("INFO", "Executor: " .. executor)',
    '',
    'local parent',
    'if gethui then parent = gethui() else parent = game:GetService("CoreGui") end',
    '',
    'pcall(function()',
    '    for _, v in pairs(parent:GetChildren()) do',
    '        if v.Name == "SMVaultGUI" then v:Destroy() end',
    '    end',
    'end)',
    '',
    'local screenGui = Instance.new("ScreenGui")',
    'screenGui.Name = "SMVaultGUI"',
    'screenGui.ResetOnSpawn = false',
    'screenGui.IgnoreGuiInset = true',
    'screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling',
    'screenGui.DisplayOrder = 999999',
    'screenGui.Enabled = true',
    'screenGui.Parent = parent',
    '',
    'local mainFrame = Instance.new("Frame")',
    'mainFrame.Name = "MainFrame"',
    'mainFrame.Size = UDim2.new(0, 450, 0, 360)',
    'mainFrame.Position = UDim2.new(0.5, -225, 0.5, -180)',
    'mainFrame.BackgroundColor3 = Color3.fromRGB(18, 18, 28)',
    'mainFrame.BorderSizePixel = 0',
    'mainFrame.Visible = true',
    'mainFrame.Parent = screenGui',
    'Instance.new("UICorner", mainFrame).CornerRadius = UDim.new(0, 12)',
    'local mainStroke = Instance.new("UIStroke", mainFrame)',
    'mainStroke.Color = Color3.fromRGB(100, 0, 255)',
    'mainStroke.Thickness = 2',
    '',
    'local titleBar = Instance.new("Frame", mainFrame)',
    'titleBar.Size = UDim2.new(1, 0, 0, 42)',
    'titleBar.BackgroundColor3 = Color3.fromRGB(100, 0, 255)',
    'titleBar.BorderSizePixel = 0',
    'Instance.new("UICorner", titleBar).CornerRadius = UDim.new(0, 12)',
    '',
    'local titleFix = Instance.new("Frame", titleBar)',
    'titleFix.Size = UDim2.new(1, 0, 0, 12)',
    'titleFix.Position = UDim2.new(0, 0, 1, -12)',
    'titleFix.BackgroundColor3 = Color3.fromRGB(100, 0, 255)',
    'titleFix.BorderSizePixel = 0',
    '',
    'local titleLabel = Instance.new("TextLabel", titleBar)',
    'titleLabel.Size = UDim2.new(1, -120, 1, 0)',
    'titleLabel.Position = UDim2.new(0, 12, 0, 0)',
    'titleLabel.BackgroundTransparency = 1',
    'titleLabel.Text = "SM-VAULT v5.0"',
    'titleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)',
    'titleLabel.TextSize = 20',
    'titleLabel.Font = Enum.Font.GothamBold',
    'titleLabel.TextXAlignment = Enum.TextXAlignment.Left',
    '',
    'local debugBtn = Instance.new("TextButton", titleBar)',
    'debugBtn.Size = UDim2.new(0, 55, 0, 28)',
    'debugBtn.Position = UDim2.new(1, -100, 0, 7)',
    'debugBtn.BackgroundColor3 = Color3.fromRGB(40, 120, 255)',
    'debugBtn.Text = "DEBUG"',
    'debugBtn.TextColor3 = Color3.fromRGB(255, 255, 255)',
    'debugBtn.TextSize = 11',
    'debugBtn.Font = Enum.Font.GothamBold',
    'debugBtn.BorderSizePixel = 0',
    'Instance.new("UICorner", debugBtn).CornerRadius = UDim.new(0, 6)',
    '',
    'local closeBtn = Instance.new("TextButton", titleBar)',
    'closeBtn.Size = UDim2.new(0, 28, 0, 28)',
    'closeBtn.Position = UDim2.new(1, -38, 0, 7)',
    'closeBtn.BackgroundColor3 = Color3.fromRGB(220, 50, 50)',
    'closeBtn.Text = "X"',
    'closeBtn.TextColor3 = Color3.fromRGB(255, 255, 255)',
    'closeBtn.TextSize = 14',
    'closeBtn.Font = Enum.Font.GothamBold',
    'closeBtn.BorderSizePixel = 0',
    'Instance.new("UICorner", closeBtn).CornerRadius = UDim.new(0, 6)',
    '',
    'local statusLabel = Instance.new("TextLabel", mainFrame)',
    'statusLabel.Size = UDim2.new(1, -20, 0, 35)',
    'statusLabel.Position = UDim2.new(0, 10, 0, 55)',
    'statusLabel.BackgroundTransparency = 1',
    'statusLabel.Text = "Script Loaded Successfully!"',
    'statusLabel.TextColor3 = Color3.fromRGB(0, 255, 100)',
    'statusLabel.TextSize = 20',
    'statusLabel.Font = Enum.Font.GothamBold',
    '',
    'local executorLabel = Instance.new("TextLabel", mainFrame)',
    'executorLabel.Size = UDim2.new(1, -20, 0, 22)',
    'executorLabel.Position = UDim2.new(0, 10, 0, 95)',
    'executorLabel.BackgroundTransparency = 1',
    'executorLabel.Text = "Executor: " .. executor',
    'executorLabel.TextColor3 = Color3.fromRGB(130, 130, 255)',
    'executorLabel.TextSize = 13',
    'executorLabel.Font = Enum.Font.GothamBold',
    '',
    'local protLabel = Instance.new("TextLabel", mainFrame)',
    'protLabel.Size = UDim2.new(1, -20, 0, 22)',
    'protLabel.Position = UDim2.new(0, 10, 0, 120)',
    'protLabel.BackgroundTransparency = 1',
    'protLabel.Text = "Protections: " .. protectionsPassed .. "/100 | Token System: ON"',
    'protLabel.TextColor3 = Color3.fromRGB(0, 200, 100)',
    'protLabel.TextSize = 13',
    'protLabel.Font = Enum.Font.GothamBold',
    '',
    'local sep = Instance.new("Frame", mainFrame)',
    'sep.Size = UDim2.new(0.85, 0, 0, 2)',
    'sep.Position = UDim2.new(0.075, 0, 0, 150)',
    'sep.BackgroundColor3 = Color3.fromRGB(100, 0, 255)',
    'sep.BorderSizePixel = 0',
    '',
    'local buyTitle = Instance.new("TextLabel", mainFrame)',
    'buyTitle.Size = UDim2.new(1, -20, 0, 22)',
    'buyTitle.Position = UDim2.new(0, 10, 0, 165)',
    'buyTitle.BackgroundTransparency = 1',
    'buyTitle.Text = "Buy Source Code:"',
    'buyTitle.TextColor3 = Color3.fromRGB(160, 160, 160)',
    'buyTitle.TextSize = 13',
    'buyTitle.Font = Enum.Font.Gotham',
    '',
    'local buyLink = Instance.new("TextLabel", mainFrame)',
    'buyLink.Size = UDim2.new(1, -20, 0, 22)',
    'buyLink.Position = UDim2.new(0, 10, 0, 188)',
    'buyLink.BackgroundTransparency = 1',
    'buyLink.Text = "https://sm-vault-xyz.vercel.app/"',
    'buyLink.TextColor3 = Color3.fromRGB(80, 140, 255)',
    'buyLink.TextSize = 13',
    'buyLink.Font = Enum.Font.GothamBold',
    '',
    'local userLabel = Instance.new("TextLabel", mainFrame)',
    'userLabel.Size = UDim2.new(1, -20, 0, 22)',
    'userLabel.Position = UDim2.new(0, 10, 0, 220)',
    'userLabel.BackgroundTransparency = 1',
    'userLabel.Text = "User: " .. player.Name .. " | ID: " .. player.UserId',
    'userLabel.TextColor3 = Color3.fromRGB(100, 100, 100)',
    'userLabel.TextSize = 12',
    'userLabel.Font = Enum.Font.Gotham',
    '',
    'local verLabel = Instance.new("TextLabel", mainFrame)',
    'verLabel.Size = UDim2.new(1, -20, 0, 22)',
    'verLabel.Position = UDim2.new(0, 10, 0, 245)',
    'verLabel.BackgroundTransparency = 1',
    'verLabel.Text = "Version: 5.0 | Rate Limit + Token"',
    'verLabel.TextColor3 = Color3.fromRGB(80, 80, 80)',
    'verLabel.TextSize = 11',
    'verLabel.Font = Enum.Font.Gotham',
    '',
    'local dbgCountLabel = Instance.new("TextLabel", mainFrame)',
    'dbgCountLabel.Size = UDim2.new(1, -20, 0, 22)',
    'dbgCountLabel.Position = UDim2.new(0, 10, 0, 270)',
    'dbgCountLabel.BackgroundTransparency = 1',
    'dbgCountLabel.Text = "Debug Logs: " .. #debugLogs .. " | Clipboard blocks: " .. clipboardBlocked',
    'dbgCountLabel.TextColor3 = Color3.fromRGB(60, 60, 60)',
    'dbgCountLabel.TextSize = 11',
    'dbgCountLabel.Font = Enum.Font.Gotham',
    '',
    'local debugFrame = Instance.new("Frame")',
    'debugFrame.Size = UDim2.new(0, 580, 0, 380)',
    'debugFrame.Position = UDim2.new(0.5, -290, 0.5, -190)',
    'debugFrame.BackgroundColor3 = Color3.fromRGB(10, 10, 18)',
    'debugFrame.BorderSizePixel = 0',
    'debugFrame.Visible = false',
    'debugFrame.Parent = screenGui',
    'Instance.new("UICorner", debugFrame).CornerRadius = UDim.new(0, 10)',
    '',
    'local dbgTitle = Instance.new("TextLabel", debugFrame)',
    'dbgTitle.Size = UDim2.new(1, 0, 0, 38)',
    'dbgTitle.BackgroundColor3 = Color3.fromRGB(40, 120, 255)',
    'dbgTitle.Text = "  DEBUG CONSOLE"',
    'dbgTitle.TextColor3 = Color3.fromRGB(255, 255, 255)',
    'dbgTitle.TextSize = 16',
    'dbgTitle.Font = Enum.Font.GothamBold',
    'dbgTitle.TextXAlignment = Enum.TextXAlignment.Left',
    'dbgTitle.BorderSizePixel = 0',
    'Instance.new("UICorner", dbgTitle).CornerRadius = UDim.new(0, 10)',
    '',
    'local dbgClose = Instance.new("TextButton", debugFrame)',
    'dbgClose.Size = UDim2.new(0, 28, 0, 28)',
    'dbgClose.Position = UDim2.new(1, -33, 0, 5)',
    'dbgClose.BackgroundColor3 = Color3.fromRGB(220, 50, 50)',
    'dbgClose.Text = "X"',
    'dbgClose.TextColor3 = Color3.fromRGB(255, 255, 255)',
    'dbgClose.TextSize = 13',
    'dbgClose.Font = Enum.Font.GothamBold',
    'dbgClose.BorderSizePixel = 0',
    'Instance.new("UICorner", dbgClose).CornerRadius = UDim.new(0, 6)',
    '',
    'local scroll = Instance.new("ScrollingFrame", debugFrame)',
    'scroll.Size = UDim2.new(1, -16, 1, -48)',
    'scroll.Position = UDim2.new(0, 8, 0, 42)',
    'scroll.BackgroundColor3 = Color3.fromRGB(5, 5, 10)',
    'scroll.BorderSizePixel = 0',
    'scroll.ScrollBarThickness = 5',
    'scroll.CanvasSize = UDim2.new(0, 0, 0, 0)',
    'scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y',
    'Instance.new("UICorner", scroll).CornerRadius = UDim.new(0, 6)',
    '',
    'local scrollLayout = Instance.new("UIListLayout", scroll)',
    'scrollLayout.SortOrder = Enum.SortOrder.LayoutOrder',
    'scrollLayout.Padding = UDim.new(0, 4)',
    '',
    'local scrollPad = Instance.new("UIPadding", scroll)',
    'scrollPad.PaddingLeft = UDim.new(0, 8)',
    'scrollPad.PaddingRight = UDim.new(0, 8)',
    'scrollPad.PaddingTop = UDim.new(0, 8)',
    '',
    'local function RefreshDebugLogs()',
    '    for _, c in pairs(scroll:GetChildren()) do',
    '        if c:IsA("Frame") then c:Destroy() end',
    '    end',
    '    local colors = { INFO = Color3.fromRGB(100, 200, 255), SUCCESS = Color3.fromRGB(80, 255, 80), WARNING = Color3.fromRGB(255, 200, 50), ERROR = Color3.fromRGB(255, 70, 70) }',
    '    for i, log in ipairs(debugLogs) do',
    '        local lf = Instance.new("Frame")',
    '        lf.Size = UDim2.new(1, -16, 0, 0)',
    '        lf.AutomaticSize = Enum.AutomaticSize.Y',
    '        lf.BackgroundColor3 = Color3.fromRGB(18, 18, 28)',
    '        lf.BorderSizePixel = 0',
    '        lf.LayoutOrder = i',
    '        lf.Parent = scroll',
    '        Instance.new("UICorner", lf).CornerRadius = UDim.new(0, 5)',
    '        local lp = Instance.new("UIPadding", lf)',
    '        lp.PaddingLeft = UDim.new(0, 8)',
    '        lp.PaddingRight = UDim.new(0, 8)',
    '        lp.PaddingTop = UDim.new(0, 4)',
    '        lp.PaddingBottom = UDim.new(0, 4)',
    '        local lt = Instance.new("TextLabel", lf)',
    '        lt.Size = UDim2.new(1, 0, 0, 0)',
    '        lt.AutomaticSize = Enum.AutomaticSize.Y',
    '        lt.BackgroundTransparency = 1',
    '        lt.Text = "[" .. log.time .. "] [" .. log.type .. "] " .. log.message',
    '        lt.TextColor3 = colors[log.type] or Color3.fromRGB(200, 200, 200)',
    '        lt.TextSize = 12',
    '        lt.Font = Enum.Font.Code',
    '        lt.TextXAlignment = Enum.TextXAlignment.Left',
    '        lt.TextWrapped = true',
    '        if log.solution and log.solution ~= "" then',
    '            local st = Instance.new("TextLabel", lf)',
    '            st.Size = UDim2.new(1, 0, 0, 0)',
    '            st.AutomaticSize = Enum.AutomaticSize.Y',
    '            st.BackgroundTransparency = 1',
    '            st.Text = "  FIX: " .. log.solution',
    '            st.TextColor3 = Color3.fromRGB(120, 255, 120)',
    '            st.TextSize = 11',
    '            st.Font = Enum.Font.Code',
    '            st.TextXAlignment = Enum.TextXAlignment.Left',
    '            st.TextWrapped = true',
    '        end',
    '    end',
    'end',
    '',
    'spawn(function()',
    '    while mainFrame and mainFrame.Parent do',
    '        pcall(function()',
    '            TweenService:Create(mainStroke, TweenInfo.new(2, Enum.EasingStyle.Sine), {Color = Color3.fromRGB(0, 150, 255)}):Play()',
    '            wait(2)',
    '            TweenService:Create(mainStroke, TweenInfo.new(2, Enum.EasingStyle.Sine), {Color = Color3.fromRGB(100, 0, 255)}):Play()',
    '            wait(2)',
    '        end)',
    '    end',
    'end)',
    '',
    'debugBtn.MouseButton1Click:Connect(function()',
    '    debugFrame.Visible = not debugFrame.Visible',
    '    if debugFrame.Visible then RefreshDebugLogs() end',
    'end)',
    '',
    'dbgClose.MouseButton1Click:Connect(function() debugFrame.Visible = false end)',
    'closeBtn.MouseButton1Click:Connect(function() screenGui:Destroy() end)',
    '',
    'local dragging = false',
    'local dragStart, startPos',
    'titleBar.InputBegan:Connect(function(input)',
    '    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then',
    '        dragging = true dragStart = input.Position startPos = mainFrame.Position',
    '    end',
    'end)',
    'titleBar.InputEnded:Connect(function(input)',
    '    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then dragging = false end',
    'end)',
    'UserInputService.InputChanged:Connect(function(input)',
    '    if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then',
    '        local delta = input.Position - dragStart',
    '        mainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)',
    '    end',
    'end)',
    '',
    'DebugLog("SUCCESS", "GUI created and visible")',
    '',
    'warn("==========================================")',
    'warn("     SM-VAULT v5.0 LOADED")',
    'warn("     User: " .. player.Name)',
    'warn("     Executor: " .. executor)',
    'warn("     Protections: " .. protectionsPassed .. "/100")',
    'warn("     Rate Limit + Token System: ACTIVE")',
    'warn("     Buy Source Code:")',
    'warn("     https://sm-vault-xyz.vercel.app/")',
    'warn("==========================================")',
    '',
    'print("script is working so it would work")'
  ].join('\n');

  res.setHeader('Content-Type', 'text/plain');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.status(200).send(lua);
}
